### ISSUE TITLE
Building packages for armhf and arm64

### ISSUE THREAD

**Issue by bensteinberg** [tommie/innernet-debian#2]
Thanks for doing this! Would you consider building for other architectures? I'm thinking of `armhf` for Raspberry Pi.

**Comment by kiwimato** [comment]
Hah, funny thing, I just hit the same issue on a Pi. :)
I could try to give it a shot in the coming weeks if I have enough time, but I can't promise anything.

```
Reading state information... Done
17 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'contrib/binary-arm64/Packages' as repository 'https://tommie.github.io/innernet-debian/debian jammy InRelease' doesn't support architecture 'arm64'
root@pi:/home/pi# 
```

**Comment by tommie** [comment]
I have no immediate plans for it, but since GitHub does all the work once the code is in, I don't see why not.

I see two alternatives:

1. Make GitHub actions cross-compile
2. Don't use GitHub actions :)

In the case of (1), we wouldn't have a way of knowing if the output even works. And I guess (2) would be annoying.

My guess is that (1) is viable with rustup. "cargo deb" does support cross-compilation.

* https://github.com/kornelski/cargo-deb#cross-compilation
* https://rust-lang.github.io/rustup/cross-compilation.html
* https://www.docker.com/blog/cross-compiling-rust-code-for-multiple-architectures/

I suppose building for both 32-bit and 64-bit ARM isn't a problem once we have rustup configured.

@kiwimato let me know if you get started, and I'll do the same.

**Comment by bensteinberg** [comment]
FWIW, I've built packages for armhf using [cross](https://github.com/cross-rs/cross). I set it up some time ago, so it may not be the state of the art. It requires an image built from this `Dockerfile`:
```
FROM rustembedded/cross:armv7-unknown-linux-gnueabihf

RUN dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y apt-transport-https wget gnupg2 && \
    (wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -) && \
    printf "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main\ndeb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-12 main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update && \
    apt-get install -y clang-12 libclang-common-12-dev libclang-12-dev libclang1-12 build-essential libsqlite3-dev:armhf && \
    apt-get purge -y apt-transport-https wget

ENV BINDGEN_EXTRA_CLANG_ARGS='-I /usr/arm-linux-gnueabihf/include/'
```
and a matching `Cross.toml`:
```
[target.armv7-unknown-linux-gnueabihf]
image = "myarm7:0.2"
```
Then, my current sequence is:
```
rustup update
cross clean --target armv7-unknown-linux-gnueabihf
cross build --release --target armv7-unknown-linux-gnueabihf
cd client/
cargo deb --package client --no-build --target=armv7-unknown-linux-gnueabihf --no-strip
```
and the package is then in `target/armv7-unknown-linux-gnueabihf/debian/innernet_1.6.0_armhf.deb`

**Comment by esbeeb** [comment]
I too wish there were straightforward arm64 packages, with no need for Docker, cross-compiling, manually setting up a rust development environment, etc.  Just the additional Debian repository.

**Comment by tommie** [comment]
I made some progress. Using rustup, but not cross.

It builds something, but I just got cargo-deb to pass, so I don't know what it built. :)

* https://github.com/tommie/innernet-debian/tree/armhf
* https://github.com/tommie/innernet-debian/actions/runs/5702873552

**Comment by tommie** [comment]
Got the workflow running, and managed to merge the "Upload repository" job so it only runs once. That's nice.

Looking at the binary with `readelf`, it seems to only require libgcc_s, libc libm, and libpthread, and that seems covered by the dependencies in Cargo.toml upstream. No hard-coded paths to sysroots, etc.

If someone could test the **armhf** artifacts, I'd appreciate it: https://github.com/tommie/innernet-debian/actions/runs/5705358612#artifacts

**Comment by tommie** [comment]
Managed to get a QEMU test running, and it can run the focal DEB on rpios lite: https://github.com/tommie/innernet-debian/actions/runs/5705802163/job/15460878521

**Comment by tommie** [comment]
Got arm64 building as well: https://github.com/tommie/innernet-debian/actions/runs/5706029389#artifacts

Test it, and tell me if it works.

**Comment by bensteinberg** [comment]
I just successfully installed `innernet_1.6.0-0ubuntu0~focal_armhf.deb` from https://github.com/tommie/innernet-debian/actions/runs/5705589809#artifacts on a Raspberry Pi Model 3 B+ running bullseye.

**Comment by tommie** [comment]
Thanks!

I got the armhf running on LibreELEC on a RPI 4B, but I don't have a WG network to connect to there, so I can't test it fully. (Not sure why they run armhf on an arm64, but whatever.)

I'll merge to main.

**Comment by tommie** [comment]
Should be available in the Debian repo now.
