### ISSUE TITLE
Support Debian bookworm

### ISSUE THREAD

**Issue by esbeeb** [tommie/innernet-debian#3]
there's a 404, after the "apt update" step

```
Err:8 https://tommie.github.io/innernet-debian/debian bookworm Release
  404  Not Found [IP: 185.199.109.153 443]
```

**Comment by tommie** [comment]
Hi.

Ah, looks like Debian has made a new release. We'll have to test that.

If you can, please check if the Ubuntu jammy packages work on Debian bookworm (either by setting the source distribution to jammy, or manually downloading the DEBs.)

**Comment by esbeeb** [comment]
Yes, specifying jammy for the release worked.

**Comment by tommie** [comment]
Ah, thanks. I'll add a symlink for bookworm shortly. Thanks for reporting and confirming!
